---
trigger:
  branches:
    include:
    - main
pool:
  vmImage: ubuntu-latest

steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'docker run -v $(System.DefaultWorkingDirectory):/source zricethezav/gitleaks:latest detect --no-git --source="/source" -f json -r /source/gitleaks-report.json -c /source/gitleaks.toml -v'
      pwsh: true
    displayName: 'Gitleaks secret scanner'
