repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.6.1
    hooks:
      - id: gitleaks
        description: Detect secrets using Gitleaks
        entry: gitleaks protect --verbose --staged --config gitleaks.toml